### PR TITLE
Security improvements on password change

### PR DESCRIPTION
**Pull request by jlaii**
Users are required to enter their current password before they can change their password, ensuring that only the actual users can change their account password.

### CODE REVIEW

**Comment by mtuckergd** [comment]
A few issues here. 

First, when the current password is invalid or not entered, there is no messaging to the user to indicate what is the problem; it simply does not update and returns to the page with changes reverted.

Second, in order to change the email address, I have to set the current password. Generally speaking, this should only be necessary when changing password. One way to resolve this would be to only check current password if a new password has been entered. However, due to this behavior, it might make more sense to separate the password change from the email change, where each (email and password) have their own update button hitting a separate endpoint. In the most extreme case, we could even separate the edit pages, but that's probably not necessary.

Finally, it's not ideal to do this check at the controller level. The best way to implement this check is on a model validation. You should be able to check if the new password is being changed and, only if that is the case, impose a check that the current password value is correct.

**Comment by jlaii** [comment]
Shouldn't an email change also require a password check though? Otherwise a malicious user could simply change the email address to be one that the malicious user owns, and they could then send a password reset to that new email address and gain control of the account.

**Comment by mtuckergd** [comment]
I suppose that's fair. At the least, we should be messaging when they don't enter the current password or it is invalid, instead of just reverting changes and returning (also should validate this in the model).

**Comment by jlaii** [comment]
closing and creating new PR to merge into 2-2-nemo-stable

**Pull request closed without merging**
